### ISSUE TITLE
Form frontend

### ISSUE THREAD

**Issue by Daxn872** [ProsperityGH/VrijwilligersHuis-Opdracht#2]
- [x] opmaak formulier css
- [x] contactgegevens
- [x] categories 
- [x] locatie
- [x] hoeveelheid
- [x] opmerkingen

**Comment by Jetvac05** [comment]
fixed

**Comment by Daxn872** [comment]
not fixed

**Comment by Jetvac05** [comment]
Hoi prosper

**Comment by Daxn872** [comment]
fixed it :)
